[package]
name = "sufremoak/fluidscripten"
version = "0.1.1"
# description = "A code generator that lets you treat WebAssembly modules like native dependencies."
license = "MIT" # OR license-file = "./LICENSE.md"
readme = "./README.md"
# repository = "https://github.com/wasmerio/wasmer-pack"

entrypoint = "wasmer-pack"